#!/bin/bash
#!/usr/bin/env bash
# This script runs an infinite loop and prints "I am invincible!!!" when it receives a SIGTERM signal (15), instead of terminating.

# Trap the SIGTERM signal (15). 
# When SIGTERM is received, the command 'echo "I am invincible!!!" ' is executed.
trap 'echo "I am invincible!!!"' SIGTERM

# Start an infinite loop
while true; do
    
    # Display the required phrase
    echo "To infinity and beyond"
    
    # Pause the execution for 2 seconds
    sleep 2
    
done
