#!/bin/bash
#!/usr/bin/env bash
# A script that displays "To infinity and beyond" indefinitely
# and reacts to SIGTERM with "I am invincible!!!"

# Define the trap at the top of the script
trap 'echo "I am invincible!!!"' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
